import * as functions from 'firebase-functions';
export declare const createUser: functions.HttpsFunction & functions.Runnable<any>;
export declare const updateUserRole: functions.HttpsFunction & functions.Runnable<any>;
export declare const deleteUser: functions.HttpsFunction & functions.Runnable<any>;
export declare const getUserProfile: functions.HttpsFunction & functions.Runnable<any>;
export declare const updateUserProfile: functions.HttpsFunction & functions.Runnable<any>;
export declare const createCompany: functions.HttpsFunction & functions.Runnable<any>;
export declare const updateCompany: functions.HttpsFunction & functions.Runnable<any>;
export declare const getCompanyUsers: functions.HttpsFunction & functions.Runnable<any>;
export declare const createDriver: functions.HttpsFunction & functions.Runnable<any>;
export declare const updateDriverStatus: functions.HttpsFunction & functions.Runnable<any>;
export declare const getDriverPerformance: functions.HttpsFunction & functions.Runnable<any>;
export declare const createVehicle: functions.HttpsFunction & functions.Runnable<any>;
export declare const updateVehicleLocation: functions.HttpsFunction & functions.Runnable<any>;
export declare const getVehicleHistory: functions.HttpsFunction & functions.Runnable<any>;
export declare const createRoute: functions.HttpsFunction & functions.Runnable<any>;
export declare const updateRouteStatus: functions.HttpsFunction & functions.Runnable<any>;
export declare const getRoutePassengers: functions.HttpsFunction & functions.Runnable<any>;
export declare const createAlert: functions.HttpsFunction & functions.Runnable<any>;
export declare const updateAlertStatus: functions.HttpsFunction & functions.Runnable<any>;
export declare const getAlerts: functions.HttpsFunction & functions.Runnable<any>;
export declare const sendNotification: functions.HttpsFunction & functions.Runnable<any>;
export declare const updateFCMToken: functions.HttpsFunction & functions.Runnable<any>;
export declare const markNotificationsRead: functions.HttpsFunction & functions.Runnable<any>;
export declare const getNotifications: functions.HttpsFunction & functions.Runnable<any>;
export declare const cleanupOldNotifications: functions.HttpsFunction & functions.Runnable<any>;
export declare const processCheckin: functions.HttpsFunction & functions.Runnable<any>;
export declare const validateCheckin: functions.HttpsFunction & functions.Runnable<any>;
export declare const getCheckinHistory: functions.HttpsFunction & functions.Runnable<any>;
export declare const onUserCreated: functions.CloudFunction<import("firebase-admin/auth").UserRecord>;
export declare const onUserDeleted: functions.CloudFunction<import("firebase-admin/auth").UserRecord>;
export declare const onCriticalAlert: functions.CloudFunction<functions.firestore.QueryDocumentSnapshot>;
export declare const onVehicleLocationUpdate: functions.CloudFunction<functions.firestore.QueryDocumentSnapshot>;
export declare const api: functions.HttpsFunction;
export declare const cleanupOldData: functions.CloudFunction<unknown>;
export declare const generateDailyReport: functions.CloudFunction<unknown>;
//# sourceMappingURL=index.d.ts.map